apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: icx-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mariusjacobs/icx-argocd.git
    targetRevision: dev
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: icx-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true