apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "icx.fullname" . }}-asm
  labels:
    app: {{ template "icx.name" . }}
    module: asm
    chart: {{ template "icx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.asm.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "icx.name" . }}
      module: asm
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "icx.name" . }}
        module: asm
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.asm.image.repository }}:{{ default .Chart.AppVersion .Values.asm.image.tag }}"
          imagePullPolicy: {{ .Values.asm.image.pullPolicy }}
          volumeMounts:
          - name: answer
            mountPath: "C:/Answer"
            readOnly: true
          env:
          - name: ICX_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: connectionstring
                key: data
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - -d
                - "{ query: '{ global { dsns { name } cultures { items { name } } } }' }"
                - -H 
                - "Content-Type: application/json"
                - -X POST
                - http://localhost/asm/all/graphql/csr/api
            failureThreshold: 2
            initialDelaySeconds: 180
            timeoutSeconds: 10
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - curl
                - --fail
                - -d
                - "{ query: '{ global { dsns { name } cultures { items { name } } } }' }"
                - -H 
                - "Content-Type: application/json"
                - -X POST
                - http://localhost/asm/all/graphql/csr/api
            failureThreshold: 30
            successThreshold: 2
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 15
          # NOTE: StartupProbe is not working for Windows containers with EKS 1.21. 
          # See: https://github.com/kubernetes/website/issues/28203
          startupProbe:
            exec:
              command:
                - powershell.exe
                - -File
                - "c:\\windows\\temp\\StartupProbe.ps1"
            failureThreshold: 30
            successThreshold: 1
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 10
          resources:
{{ toYaml .Values.asm.resources | indent 12 }}
      volumes:
      - name: answer
        secret: 
          secretName: {{ .Release.Name }}-secret
    {{- with .Values.asm.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.asm.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.asm.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
