apiVersion: v1
kind: Service
metadata:
  name: {{ template "icx.fullname" . }}-asm
  labels:
    app: {{ template "icx.name" . }}
    chart: {{ template "icx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.asm.service.type }}
  ports:
    - port: {{ .Values.asm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "icx.name" . }}
    module: asm
    release: {{ .Release.Name }}
