apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: connectionstring
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: {{ .Values.connectionString.secretId }}
      versionId: {{ .Values.connectionString.secretVersion }}