apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "icx.fullname" . }}-bsm
  labels:
    app: {{ template "icx.name" . }}
    module: bsm
    chart: {{ template "icx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.bsm.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "icx.name" . }}
      module: bsm
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "icx.name" . }}
        module: bsm
        release: {{ .Release.Name }}
    securityContext:
      windowsOptions:
        runAsUserName: "IBSADMIN"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.bsm.image.repository }}:{{ default .Chart.AppVersion .Values.bsm.image.tag }}"
          imagePullPolicy: {{ .Values.bsm.image.pullPolicy }}
          env:
            - name: BG_SERVICE
              value: "Billing"
            - name: DSN
              value: "baseline"
          volumeMounts:
          - name: answer
            mountPath: "C:/Answer"
            readOnly: true
          resources:
{{ toYaml .Values.bsm.resources | indent 12 }}
      volumes:
      - name: answer
        secret: 
          secretName: {{ .Release.Name }}-secret
    {{- with .Values.bsm.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.bsm.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.bsm.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
