apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "icx.fullname" . }}-psm
  labels:
    app: {{ template "icx.name" . }}
    module: psm
    chart: {{ template "icx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.psm.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "icx.name" . }}
      module: psm
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "icx.name" . }}
        module: psm
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.psm.image.repository }}:{{ default .Chart.AppVersion .Values.psm.image.tag }}"
          imagePullPolicy: {{ .Values.psm.image.pullPolicy }}
          volumeMounts:
          - name: answer
            mountPath: "C:/Answer"
            readOnly: true
          # command:
          # - powershell.exe
          # - -File
          # - "C:/windows/temp/Startup.ps1"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   exec:
          #     command:
          #       - curl
          #       - --fail
          #       - -d
          #       - "{ query: '{ global { dsns { name } cultures { items { name } } } }' }"
          #       - -H 
          #       - "Content-Type: application/json"
          #       - -X POST
          #       - http://localhost/asm/all/graphql/csr/api
          #   failureThreshold: 2
          #   initialDelaySeconds: 180
          #   timeoutSeconds: 10
          #   periodSeconds: 10
          # readinessProbe:
          #   exec:
          #     command:
          #       - curl
          #       - --fail
          #       - -d
          #       - "{ query: '{ global { dsns { name } cultures { items { name } } } }' }"
          #       - -H 
          #       - "Content-Type: application/json"
          #       - -X POST
          #       - http://localhost/asm/all/graphql/csr/api
          #   failureThreshold: 30
          #   successThreshold: 3
          #   initialDelaySeconds: 1
          #   timeoutSeconds: 1
          #   periodSeconds: 5
          # startupProbe:
          #   httpGet:
          #     path: /asm/all/servicelocation.svc
          #     port: http
          #   failureThreshold: 30
          #   successThreshold: 1
          #   initialDelaySeconds: 1
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          resources:
{{ toYaml .Values.psm.resources | indent 12 }}
      volumes:
      - name: answer
        secret: 
          secretName: {{ .Release.Name }}-secret
    {{- with .Values.psm.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.psm.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.psm.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
