apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "icx.fullname" . }}-psm
  labels:
    app: {{ template "icx.name" . }}
    module: psm
    chart: {{ template "icx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.psm.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "icx.name" . }}
      module: psm
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "icx.name" . }}
        module: psm
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          # image: "{{ .Values.psm.image.repository }}:{{ .Values.psm.image.tag }}"
          image: "{{ .Values.psm.image.repository }}:{{ default .Chart.AppVersion .Values.psm.image.tag }}"
          imagePullPolicy: {{ .Values.psm.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /?liveness
              port: http
          readinessProbe:
            httpGet:
              path: /?readiness
              port: http
          resources:
{{ toYaml .Values.psm.resources | indent 12 }}
    {{- with .Values.psm.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.psm.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.psm.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
