apiVersion: v1
kind: Service
metadata:
  name: {{ template "icx.fullname" . }}-psm
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-target-node-labels: "kubernetes.io/os=linux,kubernetes.io/arch=amd64"
  labels:
    app: {{ template "icx.name" . }}
    chart: {{ template "icx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.psm.service.type }}
  ports:
    - port: {{ .Values.psm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "icx.name" . }}
    module: psm
    release: {{ .Release.Name }}
